# Generated by Django 5.1.7 on 2025-04-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulos',
        ),
        migrations.AddField(
            model_name='auto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
