# Generated by Django 5.1.7 on 2025-04-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0005_rename_empleado_venta_empleado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='empleado',
            new_name='Empleado',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='metodo_pago',
            new_name='MetodoPago',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.CharField(),
        ),
    ]
